apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: globex
  namespace: demo
spec:
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: shortname
              operator: Exists
          matchLabels:
            type: "non-prod"
  template:
    metadata:
      name: 'globex-{{metadata.labels.shortname}}'
      labels:
        app: globex
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ./manifests/globex
    spec:
      destination:
        namespace: '{{metadata.labels.shortname}}'
        name: 'demo-{{metadata.labels.shortname}}'
      project: default
      source:
        path: './manifests/globex/overlays/{{metadata.labels.shortname}}'
        repoURL: https://github.com/aperture-sci/DevOps.git
        targetRevision: main
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
