apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: trio
spec:
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: shortname
              operator: Exists
          # matchLabels:
          #   type: "non-prod"
  template:
    metadata:
      name: 'trioapp-{{metadata.labels.shortname}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      annotations:
        notifications.argoproj.io/subscribe.on-sync-succeeded.grafana: trio
        argocd.argoproj.io/manifest-generate-paths: '.'
        codefresh.io/product: trio
        codefresh.io/app-group: trio
        argo.octopus.com/project: "trio"
        argo.octopus.com/environment: "{{metadata.labels.shortname}}"

    spec:
      destination:
        name: '{{cluster}}'
        namespace: '{{ns}}'
      source:
        path: 'manifests/trio-app/aperture-{{metadata.labels.shortname}}'
        repoURL: 'https://github.com/aperture-sci/DevOps'
        targetRevision: main
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
