buslog:
  image:
    tag: main-8d3a3a8
    repository: docker.io/aperturesci/buslog
  replicaCount: 2
  rollout:
    strategy:
      canary:
        steps:
          - setWeight: 20
          - pause:
              duration: 5s
          - analysis:
              templates:
                - templateName: conditional-tests
          - setWeight: 50
          - pause:
              duration: 5s
          - setWeight: 100
ctrlr:
  image:
    tag: main-3344afc
    repository: docker.io/aperturesci/ctrlr
  replicaCount: 3
  rollout:
    strategy:
      canary:
        steps:
          - setWeight: 20
          - pause:
              duration: 5s
          - analysis:
              templates:
                - templateName: conditional-tests
          - setWeight: 50
          - pause:
              duration: 5s
          - setWeight: 100
flask-ui:
  image:
    tag: main-26a8f94
    repository: docker.io/aperturesci/flask-ui
  replicaCount: 2
  rollout:
    strategy:
      canary:
        steps:
          - setWeight: 20
          - pause:
              duration: 5s
          - analysis:
              templates:
                - templateName: conditional-tests
          - setWeight: 50
          - pause:
              duration: 5s
          - setWeight: 100
