loans:
  image:
    repository: docker.io/aperturesci/accounts
    tag: main-ea7090a
    pullPolicy: Always
  replicaCount: 1
  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 50m
      memory: 64Mi
