apiVersion: v1
kind: Secret
metadata:
  name: in-cluster-secret
  namespace: high
  labels:
    argocd.argoproj.io/secret-type: cluster
    shortname: staging
    type: prod
    environment: staging
    tenant: none

type: Opaque
stringData:
  name: in-cluster
  server: https://kubernetes.default.svc
