apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rollout
spec:
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: shortname
              operator: Exists
          # matchLabels:
          #   type: "non-prod"
  template:
    metadata:
      name: 'rollout-{{metadata.labels.shortname}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io/foreground
      annotations:
        argocd.argoproj.io/compare-options: ServerSideDiff=true

    spec:
      project: default
      source:
        chart: argo-rollouts
        repoURL: https://argoproj.github.io/argo-helm
        targetRevision: 2.40.9
        helm:
          releaseName: argo-rollouts
      destination:
        namespace: argo-rollouts
        name: '{{name}}'
      syncPolicy:
        syncOptions:
          - ServerSideApply=true
          - CreateNamespace=true
          - Validate=true
          - ApplyOutOfSyncOnly=false
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
