apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argo.octopus.com/environment: dev
    argo.octopus.com/project: rhos
    argo.octopus.com/tenant: Provider

  name: color-dev
  namespace: openshift-gitops
spec:
  destination:
    name: in-cluster
    namespace: dev
  project: default
  source:
    path: manifests/color/dev-rhos
    repoURL: 'https://github.com/aperture-sci/DevOps.git'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
